# Generated by Django 4.0.8 on 2022-11-10 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('statement', models.FileField(upload_to='files/')),
            ],
        ),
        migrations.AlterField(
            model_name='upload',
            name='file',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
